import { afterEach, describe, expect, it } from 'vitest'
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import {
  detectPackageManager,
  detectPackageManagerDetailed,
  PMAmbiguousError,
  PMUnresolvedError,
  resolvePackageManager,
  type PackageManagerId,
} from '../../src/core/pm.js'

const dirs: string[] = []
function makeProject(files: Record<string, string> = {}): string {
  const dir = mkdtempSync(join(tmpdir(), 'lpm-pm-'))
  dirs.push(dir)
  for (const [name, content] of Object.entries(files)) {
    const p = join(dir, name)
    mkdirSync(dirname(p), { recursive: true })
    writeFileSync(p, content, 'utf8')
  }
  return dir
}
afterEach(() => {
  while (dirs.length > 0) rmSync(dirs.pop() as string, { recursive: true, force: true })
})

describe('detectPackageManagerDetailed：lockfile 级（§4.4 级 1）', () => {
  it('用例 1：单 pnpm-lock.yaml → pnpm（evidence lockfile）', async () => {
    const dir = makeProject({ 'pnpm-lock.yaml': '' })
    const r = await detectPackageManagerDetailed(dir)
    expect(r.pm).toBe('pnpm')
    expect(r.evidence).toEqual({ kind: 'lockfile', file: 'pnpm-lock.yaml' })
  })

  it('用例 1b：单 package-lock.json → npm', async () => {
    const dir = makeProject({ 'package-lock.json': '' })
    const r = await detectPackageManagerDetailed(dir)
    expect(r.pm).toBe('npm')
    expect(r.evidence).toEqual({ kind: 'lockfile', file: 'package-lock.json' })
  })

  it('用例 1c：lockfile 优先于 corepack 字段（pnpm-lock + packageManager npm → pnpm）', async () => {
    const dir = makeProject({
      'pnpm-lock.yaml': '',
      'package.json': JSON.stringify({ packageManager: 'npm@10.8.0' }),
    })
    expect((await detectPackageManagerDetailed(dir)).pm).toBe('pnpm')
  })
})

describe('detectPackageManagerDetailed：yarn 细分（§4.4 a/b/c）', () => {
  it('用例 2a：.yarnrc.yml 存在 → yarn-berry', async () => {
    const dir = makeProject({ 'yarn.lock': '', '.yarnrc.yml': 'nodeLinker: node-modules\n' })
    const r = await detectPackageManagerDetailed(dir)
    expect(r.pm).toBe('yarn-berry')
    expect(r.evidence).toEqual({ kind: 'lockfile', file: 'yarn.lock' })
  })

  it('用例 2b：yarn.lock 头部含 __metadata → yarn-berry', async () => {
    const dir = makeProject({ 'yarn.lock': '__metadata:\nversion: "8"\n\n# yarn lockfile v1\n' })
    expect((await detectPackageManagerDetailed(dir)).pm).toBe('yarn-berry')
  })

  it('用例 2c：yarn.lock 无 __metadata → yarn-classic', async () => {
    const dir = makeProject({
      'yarn.lock': 'THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n\n# yarn lockfile v1\n',
    })
    expect((await detectPackageManagerDetailed(dir)).pm).toBe('yarn-classic')
  })

  it('用例 2d：__metadata 在头部 4KB 之外 → yarn-classic', async () => {
    const dir = makeProject({ 'yarn.lock': 'x'.repeat(4500) + '__metadata' })
    expect((await detectPackageManagerDetailed(dir)).pm).toBe('yarn-classic')
  })

  it('用例 2e：yarn.lock 为目录（读失败 EISDIR）→ yarn-classic（§6.8）', async () => {
    const dir = makeProject()
    mkdirSync(join(dir, 'yarn.lock'))
    expect((await detectPackageManagerDetailed(dir)).pm).toBe('yarn-classic')
  })
})

describe('detectPackageManagerDetailed：歧义（§4.4 级 1 命中 ≥2）', () => {
  it.each([
    { files: ['pnpm-lock.yaml', 'package-lock.json'] },
    { files: ['pnpm-lock.yaml', 'yarn.lock'] },
    { files: ['package-lock.json', 'yarn.lock'] },
    { files: ['pnpm-lock.yaml', 'package-lock.json', 'yarn.lock'] },
  ])('用例 3：$files 共存 → PMAmbiguousError，found 固定顺序（§6.1）', async ({ files }) => {
    const dir = makeProject(Object.fromEntries(files.map((f) => [f, ''])))
    const err = await detectPackageManagerDetailed(dir).catch((e: unknown) => e)
    expect(err).toBeInstanceOf(PMAmbiguousError)
    expect((err as PMAmbiguousError).found).toEqual(files)
    expect((err as Error).message).toContain('歧义')
    expect((err as Error).message).toContain('lpm use')
  })
})

describe('detectPackageManagerDetailed：corepack 字段级（§4.4 级 2）', () => {
  it.each([
    { field: 'pnpm@12.6.0', pm: 'pnpm' },
    { field: 'npm@10.8.0', pm: 'npm' },
    { field: 'yarn@1.22.19', pm: 'yarn-classic' },
    { field: 'yarn@4.1.0', pm: 'yarn-berry' },
    { field: 'yarn@4.1.0+sha224.6b5e9', pm: 'yarn-berry' },
  ])('用例 4：$field → $pm', async ({ field, pm }) => {
    const dir = makeProject({ 'package.json': JSON.stringify({ packageManager: field }) })
    const r = await detectPackageManagerDetailed(dir)
    expect(r.pm).toBe(pm)
    expect(r.evidence).toEqual({ kind: 'corepack-field', value: field })
  })

  it('用例 4b：字段为未知 PM（bun）→ 无信号 → PMUnresolvedError', async () => {
    const dir = makeProject({ 'package.json': JSON.stringify({ packageManager: 'bun@1.1.0' }) })
    await expect(detectPackageManagerDetailed(dir)).rejects.toBeInstanceOf(PMUnresolvedError)
  })

  it('用例 4c：字段非 string / JSON 坏 / package.json 缺失 → 无信号', async () => {
    const a = makeProject({ 'package.json': JSON.stringify({ packageManager: 42 }) })
    const b = makeProject({ 'package.json': 'not json' })
    const c = makeProject()
    for (const dir of [a, b, c]) {
      await expect(detectPackageManagerDetailed(dir)).rejects.toBeInstanceOf(PMUnresolvedError)
    }
  })
})

describe('detectPackageManagerDetailed：清单级与无证据（§4.4 级 3/4）', () => {
  it('用例 5：pnpm-workspace.yaml 存在（无 lockfile 无字段）→ pnpm', async () => {
    const dir = makeProject({ 'pnpm-workspace.yaml': 'packages:\n  - apps/*\n' })
    const r = await detectPackageManagerDetailed(dir)
    expect(r.pm).toBe('pnpm')
    expect(r.evidence).toEqual({ kind: 'workspace-manifest', file: 'pnpm-workspace.yaml' })
  })

  it('用例 6：仅 package.json workspaces 字段 → PMUnresolvedError（npm/yarn 同形不可辨）', async () => {
    const dir = makeProject({ 'package.json': JSON.stringify({ workspaces: ['apps/*'] }) })
    const err = await detectPackageManagerDetailed(dir).catch((e: unknown) => e)
    expect(err).toBeInstanceOf(PMUnresolvedError)
    expect((err as Error).message).toContain('lpm use')
  })

  it('用例 7：全空目录 → PMUnresolvedError', async () => {
    const dir = makeProject()
    await expect(detectPackageManagerDetailed(dir)).rejects.toBeInstanceOf(PMUnresolvedError)
  })

  it('用例 8：rootDir 不向上探测（子目录 lockfile 不影响）', async () => {
    const dir = makeProject({ 'sub/pnpm-lock.yaml': '' })
    await expect(detectPackageManagerDetailed(dir)).rejects.toBeInstanceOf(PMUnresolvedError)
  })
})

describe('detectPackageManager 与 resolvePackageManager', () => {
  it('用例 9：detectPackageManager 与 detailed.pm 一致', async () => {
    const dir = makeProject({ 'pnpm-lock.yaml': '' })
    expect(await detectPackageManager(dir)).toBe((await detectPackageManagerDetailed(dir)).pm)
  })

  it('用例 9b：resolvePackageManager——config 四值之一 → source config 且不探测（空目录也成功）', async () => {
    const dir = makeProject() // 空目录：若探测必然抛 PMUnresolvedError
    expect(await resolvePackageManager(dir, 'npm')).toEqual({ source: 'config', pm: 'npm' })
  })

  it('用例 9c：resolvePackageManager——undefined / 运行时越界值 → 走推断', async () => {
    const dir = makeProject({ 'pnpm-lock.yaml': '' })
    expect(await resolvePackageManager(dir, undefined)).toEqual({
      source: 'detected',
      pm: 'pnpm',
      evidence: { kind: 'lockfile', file: 'pnpm-lock.yaml' },
    })
    const empty = makeProject()
    await expect(
      resolvePackageManager(empty, 'bun' as unknown as PackageManagerId),
    ).rejects.toBeInstanceOf(PMUnresolvedError)
  })
})
