// S5 spec §4.5 golden 内联样本集（裁定②）——行数组逐字节控制，免疫 git autocrlf/编辑器规范化/
// Write 工具剥 BOM（S2 账本行 26 Ruling）。维度编号对应 spec §4.5 表 #1–#14。
// skipRoundtrip: 同名异值样本（F10：rewrite→restore 不保证 byte 级还原，边界明示不设分支）
export interface RewriteSample {
  name: string
  source: string
  pkgName: string
  targetValue: string
  originalValue: string
  expectedContent: string
  changedKeys: string[]
  unchangedKeys: string[]
  skipRoundtrip?: boolean
}

const BOM = '\uFEFF'
const lf = (lines: string[]) => lines.join('\n')
const crlf = (lines: string[]) => lines.join('\r\n')

export const rewriteSamples: RewriteSample[] = [
  // ── #1 基线：LF + 2 空格 + 尾随换行
  {
    name: '#1 基线 LF+2空格+尾随换行',
    pkgName: 'lib',
    targetValue: 'link:../lib',
    originalValue: '^2.0.0',
    source: lf([
      '{',
      '  "name": "app",',
      '  "dependencies": {',
      '    "left-pad": "^1.3.0",',
      '    "lib": "^2.0.0"',
      '  },',
      '  "devDependencies": {',
      '    "typescript": "^5.0.0"',
      '  }',
      '}',
      '',
    ]),
    expectedContent: lf([
      '{',
      '  "name": "app",',
      '  "dependencies": {',
      '    "left-pad": "^1.3.0",',
      '    "lib": "link:../lib"',
      '  },',
      '  "devDependencies": {',
      '    "typescript": "^5.0.0"',
      '  }',
      '}',
      '',
    ]),
    changedKeys: ['dependencies.lib'],
    unchangedKeys: [],
  },
  // ── #2 CRLF
  {
    name: '#2 CRLF',
    pkgName: 'lib',
    targetValue: 'link:../lib',
    originalValue: '^2.0.0',
    source: crlf([
      '{',
      '  "name": "app",',
      '  "dependencies": {',
      '    "lib": "^2.0.0"',
      '  }',
      '}',
      '',
    ]),
    expectedContent: crlf([
      '{',
      '  "name": "app",',
      '  "dependencies": {',
      '    "lib": "link:../lib"',
      '  }',
      '}',
      '',
    ]),
    changedKeys: ['dependencies.lib'],
    unchangedKeys: [],
  },
  // ── #2b 混合行尾：逐行原样保留
  {
    name: '#2b 混合行尾逐行保留',
    pkgName: 'lib',
    targetValue: 'link:../lib',
    originalValue: '^2.0.0',
    source: ['{\r\n', '  "name": "app",\n', '  "dependencies": {\r\n', '    "lib": "^2.0.0"\n', '  },\r\n', '}\n'].join(''),
    expectedContent: [
      '{\r\n',
      '  "name": "app",\n',
      '  "dependencies": {\r\n',
      '    "lib": "link:../lib"\n',
      '  },\r\n',
      '}\n',
    ].join(''),
    changedKeys: ['dependencies.lib'],
    unchangedKeys: [],
  },
  // ── #3 4 空格缩进
  {
    name: '#3 4空格缩进',
    pkgName: 'lib',
    targetValue: 'link:../lib',
    originalValue: '^2.0.0',
    source: lf([
      '{',
      '    "name": "app",',
      '    "dependencies": {',
      '        "lib": "^2.0.0"',
      '    },',
      '    "devDependencies": {}',
      '}',
      '',
    ]),
    expectedContent: lf([
      '{',
      '    "name": "app",',
      '    "dependencies": {',
      '        "lib": "link:../lib"',
      '    },',
      '    "devDependencies": {}',
      '}',
      '',
    ]),
    changedKeys: ['dependencies.lib'],
    unchangedKeys: [],
  },
  // ── #3b tab 缩进
  {
    name: '#3b tab缩进',
    pkgName: 'lib',
    targetValue: 'link:../lib',
    originalValue: '^2.0.0',
    source: lf([
      '{',
      '\t"name": "app",',
      '\t"dependencies": {',
      '\t\t"lib": "^2.0.0"',
      '\t}',
      '}',
      '',
    ]),
    expectedContent: lf([
      '{',
      '\t"name": "app",',
      '\t"dependencies": {',
      '\t\t"lib": "link:../lib"',
      '\t}',
      '}',
      '',
    ]),
    changedKeys: ['dependencies.lib'],
    unchangedKeys: [],
  },
  // ── #4 BOM + LF（BOM 字节保留）
  {
    name: '#4 BOM+LF',
    pkgName: 'lib',
    targetValue: 'link:../lib',
    originalValue: '^2.0.0',
    source: BOM + lf(['{', '  "dependencies": {', '    "lib": "^2.0.0"', '  }', '}', '']),
    expectedContent: BOM + lf(['{', '  "dependencies": {', '    "lib": "link:../lib"', '  }', '}', '']),
    changedKeys: ['dependencies.lib'],
    unchangedKeys: [],
  },
  // ── #4b BOM + CRLF
  {
    name: '#4b BOM+CRLF',
    pkgName: 'lib',
    targetValue: 'link:../lib',
    originalValue: '^2.0.0',
    source: BOM + crlf(['{', '  "dependencies": {', '    "lib": "^2.0.0"', '  }', '}', '']),
    expectedContent: BOM + crlf(['{', '  "dependencies": {', '    "lib": "link:../lib"', '  }', '}', '']),
    changedKeys: ['dependencies.lib'],
    unchangedKeys: [],
  },
  // ── #5 单行依赖块（段体在一行）
  {
    name: '#5 单行依赖块',
    pkgName: 'lib',
    targetValue: 'link:../lib',
    originalValue: '^2.0.0',
    source: lf([
      '{',
      '  "name": "app",',
      '  "dependencies": { "lib": "^2.0.0", "other": "1.0.0" },',
      '  "devDependencies": {}',
      '}',
      '',
    ]),
    expectedContent: lf([
      '{',
      '  "name": "app",',
      '  "dependencies": { "lib": "link:../lib", "other": "1.0.0" },',
      '  "devDependencies": {}',
      '}',
      '',
    ]),
    changedKeys: ['dependencies.lib'],
    unchangedKeys: [],
  },
  // ── #5b 整文件单行（minified）
  {
    name: '#5b 整文件单行',
    pkgName: 'lib',
    targetValue: 'link:../lib',
    originalValue: '^2.0.0',
    source: '{"name":"app","dependencies":{"lib":"^2.0.0","other":"1.0.0"},"devDependencies":{}}',
    expectedContent: '{"name":"app","dependencies":{"lib":"link:../lib","other":"1.0.0"},"devDependencies":{}}',
    changedKeys: ['dependencies.lib'],
    unchangedKeys: [],
  },
  // ── #6 无尾随换行
  {
    name: '#6 无尾随换行',
    pkgName: 'lib',
    targetValue: 'link:../lib',
    originalValue: '^2.0.0',
    source: lf(['{', '  "dependencies": {', '    "lib": "^2.0.0"', '  }', '}']),
    expectedContent: lf(['{', '  "dependencies": {', '    "lib": "link:../lib"', '  }', '}']),
    changedKeys: ['dependencies.lib'],
    unchangedKeys: [],
  },
  // ── #7 key 乱序（devDependencies 在 dependencies 前）
  {
    name: '#7 key乱序 devDeps在前',
    pkgName: 'lib',
    targetValue: 'link:../lib',
    originalValue: '^2.0.0',
    source: lf([
      '{',
      '  "devDependencies": { "typescript": "^5.0.0" },',
      '  "dependencies": { "lib": "^2.0.0" },',
      '  "name": "app"',
      '}',
      '',
    ]),
    expectedContent: lf([
      '{',
      '  "devDependencies": { "typescript": "^5.0.0" },',
      '  "dependencies": { "lib": "link:../lib" },',
      '  "name": "app"',
      '}',
      '',
    ]),
    changedKeys: ['dependencies.lib'],
    unchangedKeys: [],
  },
  // ── #8 @scope/package 包名
  {
    name: '#8 @scope包名',
    pkgName: '@scope/lib',
    targetValue: 'link:../lib',
    originalValue: '^2.0.0',
    source: lf(['{', '  "dependencies": {', '    "@scope/lib": "^2.0.0"', '  }', '}', '']),
    expectedContent: lf(['{', '  "dependencies": {', '    "@scope/lib": "link:../lib"', '  }', '}', '']),
    changedKeys: ['dependencies.@scope/lib'],
    unchangedKeys: [],
  },
  // ── #9 多段命中（裁定③：全改 + keys 逐段；同名异值 → F10 跳过 roundtrip）
  {
    name: '#9 多段命中全改',
    pkgName: 'lib',
    targetValue: 'link:../lib',
    originalValue: '^3.0.0',
    source: lf([
      '{',
      '  "name": "app",',
      '  "dependencies": {',
      '    "lib": "^3.0.0"',
      '  },',
      '  "devDependencies": {',
      '    "lib": "^1.0.0"',
      '  }',
      '}',
      '',
    ]),
    expectedContent: lf([
      '{',
      '  "name": "app",',
      '  "dependencies": {',
      '    "lib": "link:../lib"',
      '  },',
      '  "devDependencies": {',
      '    "lib": "link:../lib"',
      '  }',
      '}',
      '',
    ]),
    changedKeys: ['dependencies.lib', 'devDependencies.lib'],
    unchangedKeys: [],
    skipRoundtrip: true,
  },
  // ── #10 仅 peer 命中（零改写，裁定①数据源）
  {
    name: '#10 仅peer命中零改写',
    pkgName: 'lib',
    targetValue: 'link:../lib',
    originalValue: '^1.0.0',
    source: lf(['{', '  "name": "app",', '  "peerDependencies": {', '    "lib": "^1.0.0"', '  }', '}', '']),
    expectedContent: lf(['{', '  "name": "app",', '  "peerDependencies": {', '    "lib": "^1.0.0"', '  }', '}', '']),
    changedKeys: [],
    unchangedKeys: [],
  },
  // ── #11 幂等命中（值已等于目标 → unchangedKeys，字节不动）
  {
    name: '#11 幂等命中',
    pkgName: 'lib',
    targetValue: 'link:../lib',
    originalValue: 'link:../lib',
    source: lf([
      '{',
      '  "name": "app",',
      '  "dependencies": {',
      '    "lib": "link:../lib",',
      '    "other": "^1.0.0"',
      '  }',
      '}',
      '',
    ]),
    expectedContent: lf([
      '{',
      '  "name": "app",',
      '  "dependencies": {',
      '    "lib": "link:../lib",',
      '    "other": "^1.0.0"',
      '  }',
      '}',
      '',
    ]),
    changedKeys: [],
    unchangedKeys: ['dependencies.lib'],
  },
  // ── #12 空段（不使扫描器脱轨）
  {
    name: '#12 空段',
    pkgName: 'lib',
    targetValue: 'link:../lib',
    originalValue: '^1.0.0',
    source: lf([
      '{',
      '  "name": "app",',
      '  "dependencies": {},',
      '  "devDependencies": {',
      '    "lib": "^1.0.0"',
      '  }',
      '}',
      '',
    ]),
    expectedContent: lf([
      '{',
      '  "name": "app",',
      '  "dependencies": {},',
      '  "devDependencies": {',
      '    "lib": "link:../lib"',
      '  }',
      '}',
      '',
    ]),
    changedKeys: ['devDependencies.lib'],
    unchangedKeys: [],
  },
  // ── #13 值形态：workspace:* / catalog:（改 workspace:* 一项）
  {
    name: '#13 值形态 workspace与catalog',
    pkgName: 'lib',
    targetValue: 'link:../lib',
    originalValue: 'workspace:*',
    source: lf([
      '{',
      '  "dependencies": {',
      '    "lib": "workspace:*",',
      '    "a": "catalog:",',
      '    "b": "^1.0.0"',
      '  }',
      '}',
      '',
    ]),
    expectedContent: lf([
      '{',
      '  "dependencies": {',
      '    "lib": "link:../lib",',
      '    "a": "catalog:",',
      '    "b": "^1.0.0"',
      '  }',
      '}',
      '',
    ]),
    changedKeys: ['dependencies.lib'],
    unchangedKeys: [],
  },
  // ── #13b 已是本地协议 file:../x（纯引擎照改，无策略）
  {
    name: '#13b 本地协议照改',
    pkgName: 'lib',
    targetValue: 'link:../lib',
    originalValue: 'file:../x',
    source: lf(['{', '  "dependencies": {', '    "lib": "file:../x"', '  }', '}', '']),
    expectedContent: lf(['{', '  "dependencies": {', '    "lib": "link:../lib"', '  }', '}', '']),
    changedKeys: ['dependencies.lib'],
    unchangedKeys: [],
  },
  // ── #14 key 含 \/ 转义（F2：合法转义写法不漏命中，key 字节形态保留）
  {
    name: '#14 转义key命中',
    pkgName: '@scope/lib',
    targetValue: 'link:../lib',
    originalValue: '^2.0.0',
    source: lf(['{', '  "dependencies": {', '    "@scope\\/lib": "^2.0.0"', '  }', '}', '']),
    expectedContent: lf(['{', '  "dependencies": {', '    "@scope\\/lib": "link:../lib"', '  }', '}', '']),
    changedKeys: ['dependencies.@scope/lib'],
    unchangedKeys: [],
  },
  // ── #14b value 含尾反斜杠 "a\\"（F1：扫描器守护——后续行不得被吞）
  {
    name: '#14b 尾反斜杠value',
    pkgName: 'lib',
    targetValue: 'link:../lib',
    originalValue: '^2.0.0',
    source: lf(['{', '  "dependencies": {', '    "weird": "a\\\\",', '    "lib": "^2.0.0"', '  }', '}', '']),
    expectedContent: lf(['{', '  "dependencies": {', '    "weird": "a\\\\",', '    "lib": "link:../lib"', '  }', '}', '']),
    changedKeys: ['dependencies.lib'],
    unchangedKeys: [],
  },
  // ── #14c 段内重复 key（F3：全改 + keys 去重；同名异值 → F10 跳过 roundtrip）
  {
    name: '#14c 段内重复key',
    pkgName: 'lib',
    targetValue: 'link:../lib',
    originalValue: '1.0.0',
    source: '{"dependencies": {"lib": "1.0.0", "other": "2.0.0", "lib": "3.0.0"}}',
    expectedContent: '{"dependencies": {"lib": "link:../lib", "other": "2.0.0", "lib": "link:../lib"}}',
    changedKeys: ['dependencies.lib'],
    unchangedKeys: [],
    skipRoundtrip: true,
  },
  // ── #14d 重复段（F3：全改 + keys 去重；同名异值 → F10 跳过 roundtrip）
  {
    name: '#14d 重复段',
    pkgName: 'lib',
    targetValue: 'link:../lib',
    originalValue: '1.0.0',
    source: '{"dependencies": {"lib": "1.0.0"}, "name": "app", "dependencies": {"lib": "2.0.0"}}',
    expectedContent: '{"dependencies": {"lib": "link:../lib"}, "name": "app", "dependencies": {"lib": "link:../lib"}}',
    changedKeys: ['dependencies.lib'],
    unchangedKeys: [],
    skipRoundtrip: true,
  },
  // ── #15 optionalDependencies 命中（OCR 修复轮补维：三改段全覆盖）
  {
    name: '#15 optionalDependencies命中',
    pkgName: 'lib',
    targetValue: 'link:../lib',
    originalValue: '^2.0.0',
    source: lf(['{', '  "optionalDependencies": {', '    "lib": "^2.0.0"', '  }', '}', '']),
    expectedContent: lf(['{', '  "optionalDependencies": {', '    "lib": "link:../lib"', '  }', '}', '']),
    changedKeys: ['optionalDependencies.lib'],
    unchangedKeys: [],
  },
]
